"""Characterization coverage for the UI router public surface."""

from __future__ import annotations

from pullbox.ui.routes import router
from tests.route_contracts import iter_api_route_contracts


def test_ui_router_manifest_remains_stable_during_decomposition() -> None:
    """Pin route paths, methods, names, and endpoint names before splitting routes."""
    manifest = [
        (
            route.path,
            tuple(sorted(route.methods or [])),
            route.name,
            route.endpoint.__name__,
        )
        for route in iter_api_route_contracts(router.routes)
    ]

    assert manifest == [
        ("/", ("GET",), "dashboard", "dashboard"),
        (
            "/htmx/dashboard/continue-reading",
            ("GET",),
            "dashboard_continue_reading_partial",
            "dashboard_continue_reading_partial",
        ),
        (
            "/htmx/dashboard/briefing",
            ("GET",),
            "dashboard_briefing_partial",
            "dashboard_briefing_partial",
        ),
        (
            "/htmx/dashboard/live-pulse",
            ("GET",),
            "dashboard_live_pulse_partial",
            "dashboard_live_pulse_partial",
        ),
        (
            "/htmx/dashboard/scoreboard",
            ("GET",),
            "dashboard_scoreboard_partial",
            "dashboard_scoreboard_partial",
        ),
        (
            "/htmx/dashboard/priorities",
            ("GET",),
            "dashboard_priorities_partial",
            "dashboard_priorities_partial",
        ),
        (
            "/htmx/dashboard/watchlist",
            ("GET",),
            "dashboard_watchlist_partial",
            "dashboard_watchlist_partial",
        ),
        (
            "/htmx/dashboard/exceptions",
            ("GET",),
            "dashboard_exceptions_partial",
            "dashboard_exceptions_partial",
        ),
        (
            "/htmx/dashboard/download-exceptions-panel",
            ("GET",),
            "dashboard_download_exceptions_panel_partial",
            "dashboard_download_exceptions_panel_partial",
        ),
        (
            "/htmx/dashboard/recent-activity",
            ("GET",),
            "dashboard_recent_activity_partial",
            "dashboard_recent_activity_partial",
        ),
        ("/series", ("GET",), "series_list", "series_list"),
        ("/series/selection-ids", ("GET",), "series_selection_ids", "series_selection_ids"),
        ("/series/add", ("GET",), "add_series_page", "add_series_page"),
        ("/series/{series_id}", ("GET",), "series_detail", "series_detail"),
        ("/downloads", ("GET",), "downloads", "downloads"),
        ("/post-processing", ("GET",), "post_processing", "post_processing"),
        ("/htmx/post-processing/queue", ("GET",), "htmx_pp_queue", "htmx_pp_queue"),
        (
            "/htmx/post-processing/queue/{download_id}/detail",
            ("GET",),
            "htmx_pp_queue_detail",
            "htmx_pp_queue_detail",
        ),
        ("/htmx/post-processing/status", ("GET",), "htmx_pp_status", "htmx_pp_status"),
        ("/htmx/post-processing/history", ("GET",), "htmx_pp_history", "htmx_pp_history"),
        ("/blocklist", ("GET",), "blocklist_page", "blocklist_page"),
        ("/htmx/blocklist", ("GET",), "htmx_blocklist", "htmx_blocklist"),
        (
            "/htmx/blocklist/{entry_id}/error-detail",
            ("GET",),
            "htmx_blocklist_error_detail",
            "htmx_blocklist_error_detail",
        ),
        ("/library/matching", ("GET",), "matching_queue", "matching_queue"),
        ("/library", ("GET",), "library", "library"),
        ("/import", ("GET",), "import_page", "import_page"),
        (
            "/import/{job_id}/progress-partial",
            ("GET",),
            "import_progress_partial",
            "import_progress_partial",
        ),
        (
            "/import/{job_id}/progress-state",
            ("GET",),
            "import_progress_state",
            "import_progress_state",
        ),
        (
            "/import/{job_id}/review-partial",
            ("GET",),
            "import_review_partial",
            "import_review_partial",
        ),
        (
            "/import/{job_id}/files/{file_id}/safety/allow-once",
            ("POST",),
            "import_review_allow_safety_file_once",
            "import_review_allow_safety_file_once",
        ),
        (
            "/import/{job_id}/files/{file_id}/safety/skip",
            ("POST",),
            "import_review_skip_safety_file",
            "import_review_skip_safety_file",
        ),
        (
            "/import/{job_id}/series/{series_id}/reconcile",
            ("GET",),
            "import_series_reconcile",
            "import_series_reconcile",
        ),
        (
            "/import/{job_id}/results-partial",
            ("GET",),
            "import_results_partial",
            "import_results_partial",
        ),
        (
            "/import/{job_id}/series/{series_id}/details-partial",
            ("GET",),
            "import_series_details_partial",
            "import_series_details_partial",
        ),
        (
            "/import/{job_id}/conflicts-partial",
            ("GET",),
            "import_conflicts_partial",
            "import_conflicts_partial",
        ),
        ("/import/{job_id}/log-panel", ("GET",), "import_log_panel", "import_log_panel"),
        (
            "/import/{job_id}/series/{series_id}/cv-search",
            ("GET",),
            "import_cv_search",
            "import_cv_search",
        ),
        ("/import/history", ("GET",), "import_history_redirect", "import_history_redirect"),
        ("/import/orphaned", ("GET",), "import_orphaned_redirect", "import_orphaned_redirect"),
        (
            "/import/orphaned/{imported_series_id}/cv-search",
            ("GET",),
            "import_orphaned_cv_search",
            "import_orphaned_cv_search",
        ),
        (
            "/import/orphaned/{imported_series_id}/recovery",
            ("GET",),
            "import_orphaned_recovery",
            "import_orphaned_recovery",
        ),
        ("/utilities", ("GET",), "utilities_page", "utilities_page"),
        ("/utilities/converter", ("GET",), "utilities_converter", "utilities_converter"),
        ("/utilities/mass-convert", ("GET",), "utilities_mass_convert", "utilities_mass_convert"),
        ("/utilities/mass-rename", ("GET",), "utilities_mass_rename", "utilities_mass_rename"),
        ("/utilities/integrity", ("GET",), "utilities_integrity", "utilities_integrity"),
        ("/utilities/db-check", ("GET",), "utilities_db_check", "utilities_db_check"),
        ("/utilities/permissions", ("GET",), "utilities_permissions", "utilities_permissions"),
        ("/utilities/export", ("GET",), "utilities_export", "utilities_export"),
        ("/settings", ("GET",), "settings", "settings"),
        ("/system", ("GET",), "system_page", "system_page"),
        ("/health", ("GET",), "health_page", "health_page"),
        ("/health/status", ("GET",), "health_status_partial", "health_status_partial"),
        ("/health/badge", ("GET",), "health_badge_partial", "health_badge_partial"),
        (
            "/health/download_clients/status",
            ("GET",),
            "health_download_clients_status_partial",
            "health_download_clients_status_partial",
        ),
        (
            "/health/download_clients",
            ("GET",),
            "health_download_clients_page",
            "health_download_clients_page",
        ),
        (
            "/health/download_clients/{subject_key}/status",
            ("GET",),
            "health_download_client_status_partial",
            "health_download_client_status_partial",
        ),
        (
            "/health/download_clients/{subject_key}",
            ("GET",),
            "health_download_client_page",
            "health_download_client_page",
        ),
        (
            "/health/indexers/status",
            ("GET",),
            "health_indexers_status_partial",
            "health_indexers_status_partial",
        ),
        ("/health/indexers", ("GET",), "health_indexers_page", "health_indexers_page"),
        (
            "/health/indexers/{subject_key}/status",
            ("GET",),
            "health_indexer_status_partial",
            "health_indexer_status_partial",
        ),
        ("/health/indexers/{subject_key}", ("GET",), "health_indexer_page", "health_indexer_page"),
        (
            "/health/{component_key}/status",
            ("GET",),
            "health_component_status_partial",
            "health_component_status_partial",
        ),
        ("/health/{component_key}", ("GET",), "health_component_page", "health_component_page"),
        ("/security", ("GET",), "security_page", "security_page"),
        ("/pull-list", ("GET",), "pull_list", "pull_list"),
        (
            "/pull-list/{series_id}/monitoring",
            ("POST",),
            "update_pull_list_monitoring",
            "update_pull_list_monitoring",
        ),
        ("/reading", ("GET",), "reading_workspace", "reading_workspace"),
        ("/htmx/series/search", ("GET",), "htmx_search_series", "htmx_search_series"),
        ("/issues/{issue_id}", ("GET",), "issue_detail", "issue_detail"),
        (
            "/htmx/issues/{issue_id}/reading",
            ("GET",),
            "htmx_issue_reading_hero",
            "htmx_issue_reading_hero",
        ),
        (
            "/htmx/issues/{issue_id}/reading-row",
            ("GET",),
            "htmx_issue_reading_row",
            "htmx_issue_reading_row",
        ),
        (
            "/htmx/issues/{issue_id}/dc-search-status",
            ("GET",),
            "htmx_issue_dc_search_status",
            "htmx_issue_dc_search_status",
        ),
        (
            "/htmx/issues/{issue_id}/dc-search-results",
            ("GET",),
            "htmx_issue_dc_search_results",
            "htmx_issue_dc_search_results",
        ),
        (
            "/htmx/issues/{issue_id}/toggle",
            ("POST",),
            "htmx_toggle_issue_status",
            "htmx_toggle_issue_status",
        ),
        (
            "/htmx/issues/{issue_id}/search-results",
            ("GET",),
            "htmx_issue_search_results",
            "htmx_issue_search_results",
        ),
        ("/htmx/series/{series_id}/delete", ("POST",), "htmx_delete_series", "htmx_delete_series"),
        (
            "/htmx/series/{series_id}/alternate-names",
            ("POST",),
            "htmx_add_alternate_name",
            "htmx_add_alternate_name",
        ),
        (
            "/htmx/series/{series_id}/alternate-names/{name}",
            ("DELETE",),
            "htmx_remove_alternate_name",
            "htmx_remove_alternate_name",
        ),
        ("/htmx/series/{series_id}/issues", ("GET",), "htmx_series_issues", "htmx_series_issues"),
        ("/htmx/downloads/queue", ("GET",), "htmx_download_queue", "htmx_download_queue"),
        ("/htmx/downloads/history", ("GET",), "htmx_download_history", "htmx_download_history"),
        (
            "/htmx/downloads/history/{download_id}/error-detail",
            ("GET",),
            "htmx_download_history_error_detail",
            "htmx_download_history_error_detail",
        ),
        ("/htmx/utilities/{tab}", ("GET",), "htmx_utilities_tab", "htmx_utilities_tab"),
        (
            "/htmx/utilities/jobs/{job_id}/detail",
            ("GET",),
            "htmx_utility_history_job_detail",
            "htmx_utility_history_job_detail",
        ),
        ("/htmx/settings/{tab}", ("GET",), "htmx_settings_tab", "htmx_settings_tab"),
        ("/htmx/system/{tab}", ("GET",), "htmx_system_tab", "htmx_system_tab"),
        ("/htmx/security/{tab}", ("GET",), "htmx_security_tab", "htmx_security_tab"),
        (
            "/htmx/matching/series",
            ("GET",),
            "htmx_matching_series_search",
            "htmx_matching_series_search",
        ),
        ("/htmx/matching/issues", ("GET",), "htmx_matching_issues", "htmx_matching_issues"),
        ("/logout", ("GET", "POST"), "ui_logout", "ui_logout"),
        ("/intervention", ("GET",), "intervention_page", "intervention_page"),
        (
            "/htmx/intervention/content",
            ("GET",),
            "htmx_intervention_content",
            "htmx_intervention_content",
        ),
        (
            "/htmx/intervention/history/{pending_id}/detail",
            ("GET",),
            "htmx_intervention_history_detail",
            "htmx_intervention_history_detail",
        ),
        ("/htmx/intervention/list", ("GET",), "htmx_intervention_list", "htmx_intervention_list"),
        (
            "/intervention/selection-ids",
            ("GET",),
            "intervention_selection_ids",
            "intervention_selection_ids",
        ),
        (
            "/htmx/intervention/count",
            ("GET",),
            "htmx_intervention_count",
            "htmx_intervention_count",
        ),
        (
            "/htmx/intervention/count-text",
            ("GET",),
            "htmx_intervention_count_text",
            "htmx_intervention_count_text",
        ),
        (
            "/htmx/intervention/bulk-approve",
            ("POST",),
            "htmx_intervention_bulk_approve",
            "htmx_intervention_bulk_approve",
        ),
        (
            "/htmx/intervention/bulk-reject",
            ("POST",),
            "htmx_intervention_bulk_reject",
            "htmx_intervention_bulk_reject",
        ),
        (
            "/htmx/intervention/{pending_id}/approve",
            ("POST",),
            "htmx_intervention_approve",
            "htmx_intervention_approve",
        ),
        (
            "/htmx/intervention/{pending_id}/reject",
            ("POST",),
            "htmx_intervention_reject",
            "htmx_intervention_reject",
        ),
        (
            "/htmx/intervention/{pending_id}/retry-recovery",
            ("POST",),
            "htmx_intervention_retry_recovery",
            "htmx_intervention_retry_recovery",
        ),
        ("/search-history", ("GET",), "search_history_page", "search_history_page"),
        (
            "/htmx/search-history/logs/{log_id}/detail",
            ("GET",),
            "search_history_log_detail",
            "search_history_log_detail",
        ),
        ("/whats-new", ("GET",), "whats_new_page", "whats_new_page"),
        ("/login", ("GET",), "login_page", "login_page"),
        ("/login", ("POST",), "login_form", "login_form"),
        ("/setup", ("GET",), "setup_page", "setup_page"),
    ]
